In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
import numpy as np
import pandas as pd
import os

In [6]:
path = '/content/drive/MyDrive/추천시스템 강의 (패스트캠퍼스)/data'
npr = pd.read_csv(os.path.join(path, 'npr.csv'), encoding='utf-8')

In [8]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [9]:
npr.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11992 entries, 0 to 11991
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Article  11992 non-null  object
dtypes: object(1)
memory usage: 93.8+ KB


In [10]:
npr['Article'][2000]


'Updated at 7:50 p. m. ET, The death toll in Wednesday’s terrorist attack near the U. K. Parliament has risen, after a    man died of his injuries. Police say Leslie Rhodes of south London is the fourth person killed by   Khalid Masood, who was killed in the attack. Other victims include Kurt Cochran of Utah, 54, whose wife was also seriously injured Police Constable Keith Palmer, 48 and Aysha Frade, 43, who was reportedly on her way to pick her children up from school. Police arrested 11 people in connection to the case, but have released eight of them with no action, and released one on bail. Providing an update on the wounded, Metropolitan Police Deputy Commissioner Mark Rowley said, ”two people remain in hospital in what is described as a critical condition, and one person is considered to have life threatening injuries.” ”Two of our officers who were injured on Westminster Bridge in the attack also remain in hospital and also have sustained significant injuries,” Rowley said. When

# Preprocessing & Vectorization

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [13]:
dtm = cv.fit_transform(npr['Article'])


In [16]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

# Implementing LDA

In [18]:
from sklearn.decomposition import LatentDirichletAllocation


We want to have 7 topic groups by using 'n_components'.

In [19]:
LDA = LatentDirichletAllocation(n_components=7,n_jobs=-1, verbose=3, random_state=42)

In [20]:
LDA.fit(dtm)

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:   26.7s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


iteration: 1 of max_iter: 10


[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:   23.4s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


iteration: 2 of max_iter: 10


[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:   21.0s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


iteration: 3 of max_iter: 10


[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:   18.9s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


iteration: 4 of max_iter: 10


[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:   17.4s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


iteration: 5 of max_iter: 10


[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:   16.0s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


iteration: 6 of max_iter: 10


[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:   15.3s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


iteration: 7 of max_iter: 10


[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:   14.7s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


iteration: 8 of max_iter: 10


[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:   14.4s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


iteration: 9 of max_iter: 10


[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:   14.1s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.


iteration: 10 of max_iter: 10


[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:   12.5s finished


LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=7, n_jobs=-1,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=3)

# Showing Stored Words
There are 54,777 unique words in the corpus.


In [21]:
len(cv.get_feature_names())


54777

In [22]:
type(cv.get_feature_names())


list

In [23]:
cv.get_feature_names()[40000]


'receiving'

# Grab the Topics

In [24]:
len(LDA.components_)


7

In [25]:
LDA.components_.shape

(7, 54777)

This confirms that we have 7 topic groups and there are 54,777 unique words. Also, each element
represents how frequent a word is for a topic group. The higher the value is, the more frequent the
corresponding word is.


In [26]:
LDA.components_


array([[9.28478663e+00, 2.37647126e+03, 1.42900582e-01, ...,
        1.43007299e-01, 1.42883592e-01, 1.42860568e-01],
       [2.74162880e+01, 5.38525743e+02, 1.42857148e-01, ...,
        1.42862118e-01, 1.42857146e-01, 1.42904641e-01],
       [6.45493261e+00, 8.03087576e+02, 1.42857148e-01, ...,
        6.14236610e+00, 2.14084440e+00, 1.42933342e-01],
       ...,
       [3.05326755e+00, 3.52354804e+02, 1.42857147e-01, ...,
        1.42860060e-01, 1.42857146e-01, 1.42870216e-01],
       [4.67160839e+01, 5.12171548e+01, 3.14281367e+00, ...,
        1.43103284e-01, 1.43692384e-01, 2.14270626e+00],
       [3.33028432e-01, 4.35314967e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43765929e-01, 1.42867829e-01]])

In [27]:
len(LDA.components_[0])


54777

We grap important scores for the first topic.

In [28]:
single_topic = LDA.components_[0]

In [29]:
# argsort() --> index positions sorted from least to greatest
# Returns the indices that would sort this array.
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

In [30]:
# Word least representative of this topic
single_topic[2475]

0.1428571430864757

In [31]:
# Word most representative of this topic
single_topic[42993]

6197.3915105662945

# Grab most frequent words per topic


In [32]:
# Top 10 words for this topic:
# Last 10 values of argsort
single_topic.argsort()[-10:]


array([33390, 36310, 21228, 31464,  8149, 10425, 36283, 22673, 42561,
       42993])

In [34]:
top_ten_words = single_topic.argsort()[-10:]

In [35]:
for index in top_ten_words:
 print(cv.get_feature_names()[index])


new
percent
government
million
care
company
people
health
said
says


Let's view all the 7 topics found.


In [36]:
for index,topic in enumerate(LDA.components_):
 print("THE TOP 15 WORDS FOR TOPIC #{}".format(index))
 print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
 print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['companies', 'money', 'year', '000', 'federal', 'new', 'percent', 'government', 'million', 'care', 'company', 'people', 'health', 'said', 'says']


THE TOP 15 WORDS FOR TOPIC #1
['house', 'military', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


THE TOP 15 WORDS FOR TOPIC #2
['way', 'world', 'family', 'home', 'day', 'water', 'time', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


THE TOP 15 WORDS FOR TOPIC #3
['care', 'don', 'years', 'new', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']


THE TOP 15 WORDS FOR TOPIC #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']


THE TOP 15 WORDS FOR TOPIC #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think',

We began with 7 topics. It's up to us to decide the optimal number of topics in LDA. If we think
that a certain topic seems to have a mix of multiple topics, we can increase the number of topics.
We can reduce the number of topics if we think certain topics are overlaped. Some use statistics
such as coherence score to find the optimal number of topics. Also, recent topic models try to
incorporate the optimal number of topics in the estimation process.

The topic modeling analysis does not tell us what each topic represents. It's up to us to label
each topic. We will use top keywords to intepret each topic group

# Attaching Discovered Topics to Original Articles


In [37]:
dtm.shape

(11992, 54777)

In [38]:
len(npr)

11992

In [39]:
topic_results = LDA.transform(dtm)

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:   13.6s finished


In [40]:
topic_results.shape


(11992, 7)

In [41]:
topic_results[0]

array([1.44617750e-02, 6.81333234e-01, 2.25373839e-04, 2.25368643e-04,
       3.03303276e-01, 2.25480031e-04, 2.25492948e-04])

We examine the first article. Each element represents how important a topic is for the group.

In [42]:
topic_results[0].round(2)

array([0.01, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [43]:
topic_results[0].argmax()

1

This means that our model thinks that the first article belongs to topic #1.

# Combining with Original Data



In [44]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [45]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 2])

In [46]:
npr['Topic'] = topic_results.argmax(axis=1)

In [47]:
npr.head(10)


Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      1
4  From photography, illustration and video, to d...      2
5  I did not want to join yoga class. I hated tho...      3
6  With a   who has publicly supported the debunk...      3
7  I was standing by the airport exit, debating w...      2
8  If movies were trying to be more realistic, pe...      3
9  Eighteen years ago, on New Year’s Eve, David F...      2